### ISSUE TITLE
slave 镜像似乎不支持访问https 的 master节点URL.

### ISSUE THREAD

**Issue by tanpengsccd** [asdjkm1234/smokeping-docker#1]
```yml
version: '3.7'
services:
  smokeping-slave:
    image: asdjkm1234/smokeping-slave:latest
    restart: always
    container_name: smokeping-slave
    environment:  
      - SMOKEPING_MASTER_URL="https://baidu.com/smokeping/smokeping.fcgi.dist"  
      - SMOKEPING_SLAVE_NAME="host1"
      - SMOKEPING_SHARED_SECRET="123456"
```
<img width="1154" alt="image" src="https://github.com/asdjkm1234/smokeping-docker/assets/13959880/c913cdcf-9026-4d0c-9b95-2624b87b3090">

**Comment by tanpengsccd** [comment]
ok 了 ,加一下 liblwp-protocol-https-perl 就行了.
![image](https://github.com/asdjkm1234/smokeping-docker/assets/13959880/e58bbc8b-1a05-4cfe-9b7d-dd01ffbf575a)


我已经build好的 slave 镜像  tanpengsccd/smokeping-https-slave

还有 compose 居然 不能把环境设置顺序乱改 必须 secret 在前, 不知道啥原理.
```

version: '3.7'
services:
  smokeping-slave:
    image: tanpengsccd/smokeping-https-slave
    restart: always
    container_name: smokeping-https-slave
    environment:  
      - SMOKEPING_MASTER_URL=https://baidu.com/smokeping/smokeping.fcgi.dist
      - SMOKEPING_SHARED_SECRET=123456
      - SMOKEPING_SLAVE_NAME=host1
```
